### ISSUE TITLE
Are websocket listeners accessible without SSO? 

### ISSUE THREAD

**Issue by N-Upchurch** [YunoHost-Apps/nodered_ynh#29]
I have set up a websocket listener at myserver.com/nodered/ws/socketName, but when POST to it, I get the html for the sign-on page returned. Is it not possible to access a listener without a login due to the YunoHost implementation? ...or am I just doing something stupid? I'm running YunoHost on a VPS, so I can't have the interface exposed.

**Comment by tituspijean** [comment]
No, it had overlooked the endpoints feature of NodeRED.
#28 *may* solve your issue. It changes the URLs and permissions of the app, but I do not know if Websockets are covered:

> * The `main` permission protects
>   * `/path`, to access to the dashboard ;
>   * all `/path/<node>` endpoints defined in the HTTP nodes (with the exception of `/path/admin`).
> * Upon installation, the selected administrator will have the `admin` permission and access to the editor at `/path/admin`

Can you try it out, and let me know if your websocket works?
`yunohost app upgrade nodered -u https://github.com/YunoHost-Apps/nodered_ynh/tree/testing`
You may need to change your POST url and give Visitors access to NodeRED's main permission.

**Comment by N-Upchurch** [comment]
Thanks for your reply. I have upgraded and added main permission to visitors. The UI is not working currently. When launching from the YunoHost launcher page, I receive a 502 Bad Gateway, and upon refresh, `domain.com/nodered/` is populated with "Welcome to the Node-RED Dashboard -- Please add some UI nodes to your flow and redeploy." 

Console: 
```
You are using the ngTouch module. 
AngularJS Material already has mobile click, tap, and swipe support... 
ngTouch is not supported with AngularJS Material! app.min.js:150:202

XHRGEThttps://domain.com/nodered/loading.html
[HTTP/2 404 Not Found 36ms]

Source map error: Error: request failed with status 404
Resource URL: https://domain.com/nodered/js/app.min.js
Source Map URL: angular-chart.min.js.map

```

Not sure what is going on with app.min.js, because it's accessible directly. 

`domain.com/nodered/ui` and `domain.com/nodered/admin` return "Cannot GET /nodered/ui" and the YunoHost launcher page respectively. I am running Firefox 89.0.2 on Ubuntu 20.04.2 LTS.

POST to `domain.com/nodered/ws/receiveWekan` returns the below in Postman, rather than the login screen:

```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
	<script type="text/javascript" src="/ynh_portal.js"></script>
	<link type="text/css" rel="stylesheet" href="/ynh_overlay.css">
	</link>
	<script type="text/javascript" src="/ynhtheme/custom_portal.js"></script>
	<link type="text/css" rel="stylesheet" href="/ynhtheme/custom_overlay.css">
	</link>
</head>

<body>
	<pre>Cannot POST /nodered/ws/receiveWekan</pre>
</body>

</html>
```

Happy to share server address with you if you like; just trying to avoid posting the URL publicly.

**Comment by tituspijean** [comment]
Thanks for testing! Clearly I need to finetune the configuration and read a bit about Websockets to test them properly.
I will try on my end, meanwhile you can delete the app and restore the backup made before upgrading (at least it will be somewhat useable, instead of totally broken).

**Comment by N-Upchurch** [comment]
Not sure how helpful this is, but I have found that I can access the ui as follows: 

* open port 1880 over ipv4 with YunoHost/Firewall
* open the following address in browser:
* `http://[SERVER-IP]:1880/nodered/admin/`

Using domain name doesn't work, and server ip doesn't work over https. 

This results in visitor access to the ui.

**Comment by N-Upchurch** [comment]
Forgive me, you can ignore the above comment. I just needed to add the Node-RED Admin permission to my user... 

I'll let you know if the websocket works.

**Comment by N-Upchurch** [comment]
The websocket listener seems to work!
