### ISSUE TITLE
Dashboard no accessible

### ISSUE THREAD

**Issue by qwertz098** [YunoHost-Apps/nodered_ynh#3]
Ynh is directing me to the SSO page when trying to access the dashboard by clicking the link icon in the upper left corner or type in .../UI in address bar.

If you like you can name me any logs to submit.

**Comment by tituspijean** [comment]
There is no such "dashboard" included in nodered_ynh, have you installed any extensions from the palette ?

Your `nginx` logs are most welcome, as for any issue related with URI access.

**Comment by qwertz098** [comment]
Dear tituspijean,

 

Thanks for replying. Of course i installed the package manually and try to access the already deployed dashboard (copied my project over from a working environment) via the button or by its address in browser’s navigation bar.

 



 

Nginx access log says this about the moment trying to access:

 

xxx.xxx.xxx.xxx - - [31/Mar/2020:16:41:12 +0200] "GET /ui HTTP/2.0" 302 550 "https://domain/nodered/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"                                            

xxx.xxx.xxx.xxx – my_name [31/Mar/2020:16:41:12 +0200] "GET /yunohost/sso/ HTTP/2.0" 200 5032 "https://domain/nodered/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0"

 

where /ui is the relative path from …/nodered for accessing the dashboard usually accessible at .../nodered/ui

 

Regards

 

Von: tituspijean <notifications@github.com> 
Gesendet: Samstag, 28. März 2020 11:03
An: YunoHost-Apps/nodered_ynh <nodered_ynh@noreply.github.com>
Cc: qwertz098 <kristian.krause@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [YunoHost-Apps/nodered_ynh] Dashboard no accessible (#3)

 

There is no such "dashboard" included in nodered_ynh, have you installed any extensions from the palette ?

Your nginx logs are most welcome, as for any issue related with URI access.

**Comment by tituspijean** [comment]
So the dashboard extension hardcodes the link of the button directly from the `settings.js` file. So I have enabled these settings and rewritten the nginx proxy_pass.

It works within my tests. You can try it by switching to the test branch.
I am waiting for the CI tests to confirm everything is alright and I will merge.
