### ISSUE TITLE
Installation failure when attempting to upgrade from 1.3.5~ynh2 to 2.0.6~ynh1

### ISSUE THREAD

**Issue by N-Upchurch** [YunoHost-Apps/nodered_ynh#35]
### Describe the bug

Installation failure when attempting to upgrade from 1.3.5~ynh2 to 2.0.6~ynh1. (Full log linked below)

```
Now upgrading nodered...
Loading installation settings...
Backing up Node-RED before upgrading (may take a while)...
Ensuring downward compatibility...
Permission 'nodered.ui' already exists
[Error] Upgrade failed.
The app was restored to the way it was before the failed upgrade.
Could not upgrade nodered: An error occurred inside the app upgrade script
```

### Context
- Hardware: VPS bought online
- YunoHost version: 4.2.8.3
- I have access to my server: Through SSH & through the webadmin
- No particular tweaking on my YunoHost instance

### Steps to reproduce
Attempt to upgrade from 1.3.5~ynh2 to 2.0.6~ynh1 via web interface.

### Expected behavior
Installation to complete succesfully

### Logs
[nodered_ynh install failure log at paste.yunohost.org](https://paste.yunohost.org/raw/hopawutano)

**Comment by tituspijean** [comment]
Thank you for your report! Indeed I had botched the backward compatibility tests. Can you try the testing branch?

`yunohost app upgrade nodered -u https://github.com/YunoHost-Apps/nodered_ynh/tree/testing -F`

**Comment by N-Upchurch** [comment]
That fixed it; thanks so much!
