### ISSUE TITLE
Overriding the settings?

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/nodered_ynh#47]
# Use case

As a user, I would like to be able to add a storage for some of my Node-Red contexts, so I keep their values as i re-deploy flows or even restart the application.

To do so, I have to change the settings.js file as explained in this documentation : <https://nodered.org/docs/user-guide/context#saving-context-data-to-the-file-system>.

# Current behavior

The installation script puts a `settings.js` file into `$final_path/data`. The [upgrade script seems to do the same](https://github.com/YunoHost-Apps/nodered_ynh/blob/48ac205c8b3d7b7047b77a3d3020756b84971a6d/scripts/upgrade#L172), overriding the potential changes brought by the user.

# Proposal

If you agree on the use case and on the above premises, I would suggest to add a file to inject specific user settings and one dedicated to the settings installed by default by Yunohost:

settings.js:
```js
/**
 * This is the default settings file provided by Node-RED.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE. Rather go to and edit `__FINAL_PATH__/settings.user.js` 
 * [...]
 **/

module.exports = {
  /* 
   * <put here the same content as currently>
   * ....
   */
  ...require('./settings.user.js')(), // use require and JS destructuration to fetch the user settings, add and possibly override the above settings
};
```

settings.user.js:
```js
/**
 * This is where you you can as a user define and even override the default settings. 
 * This file will remain untouched by the yunohost package accross upgrades.
 *
 * It can contain any valid JavaScript code that will get run when Node-RED
 * is started.
 *
 * Lines that start with // are commented out.
 * Each entry should be separated from the entries above and below by a comma ','
 *
 * For more information about individual settings, refer to the documentation:
 *    https://nodered.org/docs/user-guide/runtime/configuration
 *
 * The settings are split into the following sections:
 *  - Flow File and User Directory Settings
 *  - Security
 *  - Server Settings
 *  - Runtime Settings
 *  - Editor Settings
 *  - Node Settings
 *
 **/

module.exports = {
  // This is where you can add settings
};
```

**Comment by tituspijean** [comment]
That's a great idea if that works. :) Feel free to make a PR. 😉

**Comment by fflorent** [comment]
Current status:

![image](https://c.tenor.com/CG_1SY92WUwAAAAC/christmas-keyboard.gif)
