### ISSUE TITLE
Cannot install node-red-node-email

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/nodered_ynh#63]
### Describe the bug

In NodeRED, go to the palette manager and attempt the installation of `node-red-node-email`: the installation fails.

### Steps to reproduce

   1. From the administration of nodered (`https://domain.tld/nodered/admin`)
   2. Press Alt-Shift-P to open the panel manager
   3. Select the `Install` tab
   4. Search for `node-red-node-email` and install it

### Expected behavior

The installation should succeed, but it fails

### Logs

```
févr. 16 10:59:16 zeteo.me node[3347]: 16 Feb 10:59:16 - [info]  - node-red-node-email:e-mail : SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 97 (Unknown system error 97)
févr. 16 10:59:16 zeteo.me node[3347]: 16 Feb 10:59:16 - [info]  - node-red-node-email:e-mail in : SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 97 (Unknown system error 97)
févr. 16 10:59:16 zeteo.me node[3347]: 16 Feb 10:59:16 - [info]  - node-red-node-email:e-mail mta : SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_interface_addresses returned Unknown system error 97 (Unknown system error 97)
```

### Note

This bug is similar to https://github.com/YunoHost-Apps/peertube_ynh/issues/283

**Comment by tituspijean** [comment]
To be fixed upon merging of #65
