### ISSUE TITLE
Is the updater.sh script running? (PR for version 3.0.1 missing)

### ISSUE THREAD

**Issue by fflorent** [YunoHost-Apps/nodered_ynh#68]
[Version 3.0.1](https://github.com/node-red/node-red/blob/master/CHANGELOG.md) of NodeRed has been released. I don't see any PR for this version despite the presence of the existence of the `.github/workflows/updater.sh` script. Is this script running?

Thanks in advance! :pray:

**Comment by tituspijean** [comment]
Thank you for the ping! After 60 days without new outputs, the Actions get disabled. I have reenabled it.

**Comment by fflorent** [comment]
You're welcome! Shouldn't the timeout have a greater value then? (if new outputs means that a new version is published)

**Comment by tituspijean** [comment]
Yup... but that's Github's fault. We have no ways to tune that. I a considering having a bot which manually relaunches the auto-updaters once a month to avoid that.
