### ISSUE TITLE
Admin ui loads partially, some assets get "You've been SSOed"

### ISSUE THREAD

**Issue by arthurlutz** [YunoHost-Apps/nodered_ynh#78]
### Describe the bug

The /nodered/admin/ URL loads partially, making the application unusable. 

![image](https://github.com/YunoHost-Apps/nodered_ynh/assets/108437/27212371-4386-453f-b1a6-e88ca684b578)

It seems to fail on `/nodered/admin/red/images/deploy-full-o.svg` with the infamous "You've been SSOed" yet I am logged it, tried to change firefox containers etc. 

I also get a `Content Security Policy: The page’s settings blocked the loading of a resource at wss://example.org/nodered/admin/comms (“default-src”).` which is probably the culprit... 

### Context

- Hardware: *Old laptop or computer*
- YunoHost version: 11.1.20 (stable)
- I have access to my server: *Through SSH | through the webadmin | direct access via keyboard / screen | ...*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: upgraded numerous times
- Using, or trying to install package version/branch: testing

**Comment by arthurlutz** [comment]
Just hacked my way into it working with the attached commit (local nginx config change for now on my install).

**Comment by OniriCorpe** [comment]
done with the v3.1.4~ynh2 ^w^
thank you
